#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
if [ "$#" -ge 3 ] && ([ $1 == "consumer" ] || [ $1 == "producer" ]);
then
	if [[ $2 =~ ^-?[0-9]+$ ]] && ([ "$#" -ne 4 ] || [[ $4 =~ ^-?[0-9]+(\.[0-9]+)?$ ]])
	then
		for ((i = 1; i <= $2; i++)); do
    		./${1} ${3} &
		done
	else
		echo "Quantity or Mean are not numbers"
	fi
else
	echo "Command not recognized, available commands are:"
	echo "	./bulk consumer quantity bufferName"
	echo "	./bulk producer quantity bufferName"
fi
